src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact_Status__c</fullName>
        <label>Contact Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pre-MQL</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>MQL</fullName>
                </value>
                <value>
                    <fullName>Engaged</fullName>
                </value>
                <value>
                    <fullName>Timing - Future Opportunity</fullName>
                </value>
                <value>
                    <fullName>SQL</fullName>
                </value>
                <value>
                    <fullName>In Sequence</fullName>
                </value>
                <value>
                    <fullName>No Response</fullName>
                </value>
                <value>
                    <fullName>Disqualified</fullName>
                </value>
                <value>
                    <fullName>Added to Existing Account - Not in Sequence</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Bad Data - No Longer at Company</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Bad Data - Other</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Bad Data - Wrong Contact Info</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Completed Sequence and Unresponsive</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Contacted - CAS</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Contacted - In Sequence</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Contacted and Disqualified - No Budget</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Contacted and Disqualified - Not the Right Person</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Contacted and Disqualified - Not the Right Time</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Contacted and Disqualified - Other</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Contacted and Disqualified - Prefers Existing Solution</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Contacted and Disqualified - Product Does Not Fit Need</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Contacted and Disqualified - Unresponsive</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Contacted and Sales Qualified - New Opportunity</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Do Not Contact - Blacklisted</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Do Not Contact - Unsubscribed</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Manual_Finish_and_Unresponsive</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Marketing Qualified</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Not Contacted and Disqualified - Not a Valid Title</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Not Contacted and Disqualified - Not in Target Market</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Not in Outbound Funnel</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Lead_Class__c</fullName>
        <label>Lead Class</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Inbound</fullName>
                </value>
                <value>
                    <fullName>SDR Outbound</fullName>
                </value>
                <value>
                    <fullName>AE Outbound</fullName>
                </value>
                <value>
                    <fullName>Outbound</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Secondary_Lead_Source__c</fullName>
        <inlineHelpText>The source from which the prospect came to submit their contact information (as determined by Primary Lead Source).</inlineHelpText>
        <label>Secondary Lead Source</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Organic</fullName>
                </value>
                <value>
                    <fullName>Direct</fullName>
                </value>
                <value>
                    <fullName>LinkedIn Ads</fullName>
                </value>
                <value>
                    <fullName>Facebook Ads</fullName>
                </value>
                <value>
                    <fullName>Google AdWords</fullName>
                </value>
                <value>
                    <fullName>Website Referral</fullName>
                </value>
                <value>
                    <fullName>Partner Referral</fullName>
                </value>
                <value>
                    <fullName>Customer Referral</fullName>
                </value>
                <value>
                    <fullName>Conference</fullName>
                </value>
                <value>
                    <fullName>Hosted Event</fullName>
                </value>
                <value>
                    <fullName>Node</fullName>
                </value>
                <value>
                    <fullName>List Purchase</fullName>
                </value>
                <value>
                    <fullName>LinkedIn Sales Navigator</fullName>
                </value>
                <value>
                    <fullName>Intra-Account Referral</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Opportunity_Inbound_Outbound__c</fullName>
        <label>Lead Class</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Inbound</fullName>
                </value>
                <value>
                    <fullName>SDR Outbound</fullName>
                </value>
                <value>
                    <fullName>AE Outbound</fullName>
                </value>
                <value>
                    <fullName>Outbound</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Secondary_Lead_Source__c</fullName>
        <inlineHelpText>The source from which the prospect came to submit their contact information (as determined by Primary Lead Source).</inlineHelpText>
        <label>Secondary Lead Source</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Organic</fullName>
                </value>
                <value>
                    <fullName>Direct</fullName>
                </value>
                <value>
                    <fullName>LinkedIn Ads</fullName>
                </value>
                <value>
                    <fullName>Facebook Ads</fullName>
                </value>
                <value>
                    <fullName>Google AdWords</fullName>
                </value>
                <value>
                    <fullName>Website Referral</fullName>
                </value>
                <value>
                    <fullName>Partner Referral</fullName>
                </value>
                <value>
                    <fullName>Customer Referral</fullName>
                </value>
                <value>
                    <fullName>Conference</fullName>
                </value>
                <value>
                    <fullName>Hosted Event</fullName>
                </value>
                <value>
                    <fullName>Node</fullName>
                </value>
                <value>
                    <fullName>List Purchase</fullName>
                </value>
                <value>
                    <fullName>LinkedIn Sales Navigator</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Round_Robin_Assignee__c.object
<CustomObject>
    <fields>
        <fullName>Assignee_Id__c</fullName>
        <label>Assignee Id</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Round_Robin_Assignees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Round_Robin_Setup__c</fullName>
        <label>Round Robin Setup</label>
        <referenceTo>Round_Robin_Setup__c</referenceTo>
        <relationshipLabel>Round Robin Assignees</relationshipLabel>
        <relationshipName>Round_Robin_Assignees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Round Robin Assignee</label>
    <nameField>
        <displayFormat>RRA-{000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Round Robin Assignees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Round_Robin_Setup__c.object
<CustomObject>
    <fields>
        <fullName>Next_Assignee__c</fullName>
        <label>Next Assignee</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Special_Assignee__c</fullName>
        <label>Special Assignee</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Account</fullName>
                </value>
                <value>
                    <fullName>Opportunity</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Round Robin Setup</label>
    <nameField>
        <label>Round Robin Set Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Round Robin Setups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>AccountsCount__c</fullName>
        <label>AccountsCount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/Test_ContactRelatedContacts.cls
@isTest (SeeAllData = false)

public class Test_ContactRelatedContacts {

    public static testMethod void FindoutHowmuch(){
         List<Profile> ps = [select id, name from Profile where  name = 'AE'];
        List<user> usrlst = new List<user>();
        for(integer i = 0;i<5;i++){
            User standard = new User(alias = 'standt'+i, AccountsCount__c = 0,
                                 email='standarduser'+i+'@testorg.com', 
                                 emailencodingkey='UTF-8', 
                                 lastname='Testing', languagelocalekey='en_US', 
                                 localesidkey='en_US', 
                                 profileid = ps[0].Id, 
                                 timezonesidkey='America/Los_Angeles', 
                                 username='standarduserzzi8'+i+'@testorg.com');
            usrlst.add(standard);
            
        } 
        insert usrlst;
         Round_Robin_Setup__c rrs = new Round_Robin_Setup__c(Name = 'account',Type__c = 'Account',
                                                           Special_Assignee__c = 4,Next_Assignee__c =1);
        insert rrs;
         Round_Robin_Setup__c rrs1 = new Round_Robin_Setup__c(Name = 'Opp',Type__c = 'Opportunity',
                                                           Special_Assignee__c = 4,Next_Assignee__c =1);
         insert rrs1;
        List<Round_Robin_Assignee__c> rralist = new List<Round_Robin_Assignee__c>();
        for(Integer i=0;i<5;i++){
            Round_Robin_Assignee__c rra = new Round_Robin_Assignee__c();
                 rra.Assignee_Id__c = i;
                rra.Round_Robin_Setup__c = rrs.id;
                rra.Owner__c = usrlst[i].Id;
             rralist.add(rra);
        }
        for(Integer i=0;i<5;i++){
            Round_Robin_Assignee__c rra = new Round_Robin_Assignee__c();
            rra.Assignee_Id__c = i;
            rra.Round_Robin_Setup__c = rrs1.id;
            rra.Owner__c = usrlst[i].Id;
            rralist.add(rra);
        }
           insert rralist;
        List<account> acs = new List<account>();
        for(integer i=1;i<8;i++){
            account ac = new account(name = 'test'+i,Website= 'test'+i);
            acs.add(ac);
        }
        insert acs;
        List<Opportunity> opps = new List<Opportunity>();
        Id recId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('New or Add-On').getRecordTypeId();
 
        for(integer i=1;i<4;i++){
            Opportunity opac = new Opportunity(name = 'test'+i,AccountId = acs[i-1].Id );
            opac.Opportunity_Inbound_Outbound__c = 'SDR Outbound';
            opac.stageName = '00-Qualification';
            opac.Secondary_Lead_Source__c = 'Organic';
            opac.CloseDate = system.today().adddays(+30);
            opac.RecordTypeId = recId;
            opac.LeadSource='Chat';
            opac.Secondary_Lead_Source__c='Direct';
            opps.add(opac);
        }
        Opportunity opac = new Opportunity(name = 'test',AccountId = acs[ 1].Id );
        opac.Opportunity_Inbound_Outbound__c = 'Inbound';
        opac.stageName = '00-Qualification';
        opac.CloseDate = system.today().adddays(+30);
        opac.RecordTypeId = recId;
        opac.LeadSource='Chat';
        opac.Secondary_Lead_Source__c='Conference';
        opps.add(opac);
        insert opps;
        
        Account ac01 = New Account();
        ac01.Name = 'abc';
        ac01.Website = 'www.google.com';
        ac01.Type = 'Prospect';
        insert ac01;
        
        Contact c01 = New Contact();
        c01.LastName = 'xyz';
        c01.AccountId = ac01.Id;
        c01.Title='Mr';
        c01.Email='a@b.com';
        c01.Lead_Class__c='Inbound';
        c01.LeadSource='Chat';
        c01.Secondary_Lead_Source__c='Direct';
        c01.Contact_Status__c='Pre-MQL';
        
        Contact c02 = New Contact();
        c02.LastName = 'xyz';
        c02.AccountId = ac01.Id;
        c02.Title='Mr';
        c02.Email='a@b.com';
        c02.Lead_Class__c='Inbound';
        c02.LeadSource='Chat';
        c02.Secondary_Lead_Source__c='Direct';
        c02.Contact_Status__c='Pre-MQL';
        
         Test.startTest();
            
            insert c01;
            update c01;
            insert c02;
            delete c01;
            update ac01;
        Test.StopTest();
        
        
    }
}