src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>DoNotDelete__c</fullName>
        <defaultValue>false</defaultValue>
        <label>DoNotDelete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Lead_Inbound_Outbound__c</fullName>
        <label>Lead Class</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Inbound</fullName>
                </value>
                <value>
                    <fullName>SDR Outbound</fullName>
                </value>
                <value>
                    <fullName>AE Outbound</fullName>
                </value>
                <value>
                    <fullName>Outbound</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Secondary_Lead_Source__c</fullName>
        <inlineHelpText>The source from which the prospect came to submit their contact information (as determined by Primary Lead Source).</inlineHelpText>
        <label>Secondary Lead Source</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Direct</fullName>
                </value>
                <value>
                    <fullName>Organic</fullName>
                </value>
                <value>
                    <fullName>LinkedIn Ads</fullName>
                </value>
                <value>
                    <fullName>Facebook Ads</fullName>
                </value>
                <value>
                    <fullName>Google AdWords</fullName>
                </value>
                <value>
                    <fullName>Website Referral</fullName>
                </value>
                <value>
                    <fullName>Partner Referral</fullName>
                </value>
                <value>
                    <fullName>Customer Referral</fullName>
                </value>
                <value>
                    <fullName>Conference</fullName>
                </value>
                <value>
                    <fullName>Hosted Event</fullName>
                </value>
                <value>
                    <fullName>Node</fullName>
                </value>
                <value>
                    <fullName>List Purchase</fullName>
                </value>
                <value>
                    <fullName>LinkedIn Sales Navigator</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/classes/DeleteTriggerTest.cls
@isTest

public class DeleteTriggerTest {

    public static testMethod void Test(){
    

List<Lead> le = [SELECT Id, OwnerId,CreatedById,Lead_Inbound_Outbound__c, CreatedDate FROM
                                                  Lead WHERE DoNotDelete__c = false AND OwnerId = '005370000011vYz'];
                                                  
  Lead l = new Lead();
  l.DoNotDelete__c = false;
  l.LastName = 'xyzs';
  l.Company = 'ABCS';
  l.Status = 'Pre-MQL';
  l.LeadSource = 'Webform';
  l.Lead_Inbound_Outbound__c='SDR Outbound';
  l.Secondary_Lead_Source__c = 'Direct';
  
  test.startTest();
  insert l; 
  delete l;
  test.stopTest();

}
}