src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Number_of_Contacts_Roles_Assigned__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Number of Contacts</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunity_Inbound_Outbound__c</fullName>
        <label>Lead Class</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Inbound</fullName>
                </value>
                <value>
                    <fullName>SDR Outbound</fullName>
                </value>
                <value>
                    <fullName>AE Outbound</fullName>
                </value>
                <value>
                    <fullName>Outbound</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Secondary_Lead_Source__c</fullName>
        <inlineHelpText>The source from which the prospect came to submit their contact information (as determined by Primary Lead Source).</inlineHelpText>
        <label>Secondary Lead Source</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Organic</fullName>
                </value>
                <value>
                    <fullName>Direct</fullName>
                </value>
                <value>
                    <fullName>LinkedIn Ads</fullName>
                </value>
                <value>
                    <fullName>Facebook Ads</fullName>
                </value>
                <value>
                    <fullName>Google AdWords</fullName>
                </value>
                <value>
                    <fullName>Website Referral</fullName>
                </value>
                <value>
                    <fullName>Partner Referral</fullName>
                </value>
                <value>
                    <fullName>Customer Referral</fullName>
                </value>
                <value>
                    <fullName>Conference</fullName>
                </value>
                <value>
                    <fullName>Hosted Event</fullName>
                </value>
                <value>
                    <fullName>Node</fullName>
                </value>
                <value>
                    <fullName>List Purchase</fullName>
                </value>
                <value>
                    <fullName>LinkedIn Sales Navigator</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Round_Robin_Assignee__c.object
<CustomObject>
    <fields>
        <fullName>Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Round_Robin_Assignees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Round_Robin_Setup__c</fullName>
        <label>Round Robin Setup</label>
        <referenceTo>Round_Robin_Setup__c</referenceTo>
        <relationshipLabel>Round Robin Assignees</relationshipLabel>
        <relationshipName>Round_Robin_Assignees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Round Robin Assignee</label>
    <nameField>
        <displayFormat>RRA-{000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Round Robin Assignees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Round_Robin_Setup__c.object
<CustomObject>
    <fields>
        <fullName>Next_Assignee__c</fullName>
        <label>Next Assignee</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Account</fullName>
                </value>
                <value>
                    <fullName>Opportunity</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Round Robin Setup</label>
    <nameField>
        <label>Round Robin Set Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Round Robin Setups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/updatecontactrolecount_Test.cls
@isTest
private class updatecontactrolecount_Test {
    
    static testMethod void TestAccount()
    {     
        Round_Robin_Setup__c robinsetup = new Round_Robin_Setup__c();
            robinsetup.Type__c = 'Account';
            robinsetup.Next_Assignee__c = 0;
         insert robinsetup;
         
        Round_Robin_Assignee__c robinassign = new Round_Robin_Assignee__c();
        robinassign.Round_Robin_Setup__c  = robinsetup.id;
        insert robinassign;
           
         Id p = [select id from profile where name='System Administrator'].id;

        User user = new User(alias = 'test123', email='test123comm@example.com',
                emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US',
                localesidkey='en_US', profileid = p, country='United States',IsActive =true,
                UserRole = [Select id From userrole  LIMIT 1],
                timezonesidkey='America/NEW_YORK', username='test123comm@exam.com'); 

        insert user;
        
        Round_Robin_Setup__c robinsetup2 = new Round_Robin_Setup__c();
        robinsetup2.Type__c = 'Opportunity';
        robinsetup2.Next_Assignee__c = 0;
        insert robinsetup2;
        Round_Robin_Assignee__c robinassign2 = new Round_Robin_Assignee__c();
        robinassign2.Round_Robin_Setup__c  = robinsetup2.id;
        robinassign2.Owner__c = user.id;
        insert robinassign2;
        
              
     
        
                
       Id recId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('New or Add-On').getRecordTypeId();
       Opportunity Opp = new Opportunity();
       Opp.Number_of_Contacts_Roles_Assigned__c=2;
        Opp.Name='Test';
        Opp.OwnerID=user.Id;
        Opp.StageName='00 - Qualification';
        Opp.CloseDate=System.today().addDays(6);
        Opp.Secondary_Lead_Source__c = 'Organic';
        Opp.Opportunity_Inbound_Outbound__c = 'SDR Outbound';
        Opp.LeadSource='Chat';
        Opp.RecordTypeId = recId;
        Opp.AccountID =  System.Label.Live_Account_ID;
          
        insert Opp;
 
      System.assertEquals(2, Opp.Number_of_Contacts_Roles_Assigned__c); 
    }   
}